name: env-multipleye3.9
channels:
  - conda-forge
  - defaults
dependencies:
  - pip==22.3.1
  - psychopy==2022.2.5
  - pip:
      - pygame==2.1.2
      - git+https://github.com/theDebbister/PyGaze # pygaze